"""Added many to may tables

Revision ID: 10690409689c
Revises: a2e622c77d11
Create Date: 2023-11-21 00:35:43.309170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10690409689c'
down_revision: Union[str, None] = 'a2e622c77d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos_stakeholders',
    sa.Column('grupo_id', sa.BigInteger(), nullable=False),
    sa.Column('stakeholder_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholders.id'], ),
    sa.PrimaryKeyConstraint('grupo_id', 'stakeholder_id')
    )
    op.create_table('secciones_profesores',
    sa.Column('profesor_id', sa.BigInteger(), nullable=False),
    sa.Column('seccion_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesores.id'], ),
    sa.ForeignKeyConstraint(['seccion_id'], ['secciones.id'], ),
    sa.PrimaryKeyConstraint('profesor_id', 'seccion_id')
    )
    op.alter_column('cursos', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cursos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_cursos_codigo', table_name='cursos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cursos_codigo', 'cursos', ['codigo'], unique=False)
    op.alter_column('cursos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cursos', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table('secciones_profesores')
    op.drop_table('grupos_stakeholders')
    # ### end Alembic commands ###
