"""create grupos table

Revision ID: b6e3c68c3bad
Revises: 774fa2a3b6fb
Create Date: 2023-11-17 02:48:25.888999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e3c68c3bad'
down_revision: Union[str, None] = '774fa2a3b6fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('proyecto', sa.String(), nullable=True),
    sa.Column('correlativo', sa.Integer(), nullable=True),
    sa.Column('borrado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_correlativo'), 'grupos', ['correlativo'], unique=False)
    op.create_index(op.f('ix_grupos_id'), 'grupos', ['id'], unique=False)
    op.create_index(op.f('ix_grupos_nombre'), 'grupos', ['nombre'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_grupos_nombre'), table_name='grupos')
    op.drop_index(op.f('ix_grupos_id'), table_name='grupos')
    op.drop_index(op.f('ix_grupos_correlativo'), table_name='grupos')
    op.drop_table('grupos')
